adding getClassroomRoster endponit
jb-1980/khan-graphql pull request #35
Opened 2022-02-03 12:48 UTC by DSerejo

getStudentsList seemes to have been removed from khan. getClassroomRoster will be used instead

2022-02-03 13:53 UTC, jb-1980 requested changes

2022-02-03 13:53 UTC, jb-1980 commented on src/index.ts
> +  }) => {
```suggestion
  getClassroomRoster = async ({
    classId,
    teacherKaid,
    pageSize = 40
  }: {
    classId: string
    teacherKaid: string
    pageSize?: number
  }) => {
```

I think we want both the `classId` and the `teacherKaid` to be required based on the query, i.e. it requires `String!`.

2022-02-09 16:55 UTC, DSerejo commented on src/index.ts
> +  }) => {
Agreed

2022-02-09 18:34 UTC, jb-1980 approved these changes

2022-02-09 18:34 UTC, merged